### ISSUE TITLE
[YLXD41YL] Ceiling Yeelight YAML Suggestion

### ISSUE THREAD

**Issue by jaddel** [syssi/esphome-yeelight-ceiling-light#8]
I flashed my YLXD41YL Ceiling Yeelight with ESPHome partly following your configuration. 

Disabling gamma correction and defining 9765Hz frequency for the ledc improved the usability a lot for me. 

Here is my yaml config. [Link](https://github.com/jaddel/ESPHome-Configurations/blob/master/Devices/Ceiling%20Yeelight%20YLXD41YL/ceiling_yeelight_ylxd41xl.yaml)

Do you know if there is a way to calibrate the brightness percentage? My light turns already off below 10% brightness. If i leave the gamma correction to default it already turns off at 40%.

**Comment by syssi** [comment]
I've disabled the gamma correction too. Otherwise the light turns off at a brightness of ~24% (cp. https://github.com/esphome/esphome-core/issues/190)

I will try to adjust the fequency and provide some feedback. I don't use the lights at the lower limit. Most of the time I switch between nightlight mode and daylight mode. 

Could you provide some details about your device? I would like to extend the list of supported devices.

**Comment by syssi** [comment]
Do you know the miio model name (`yeelink.light.ceilingXX?`) of the device?

**Comment by jaddel** [comment]
Inside the app its called Ceiling Light 320 1S.

**Comment by syssi** [comment]
Thanks for your support! I would like to copy & resize your image into this repository. Do go agree with the Apache 2.0 license?

**Comment by jaddel** [comment]
yes

**Comment by syssi** [comment]
@jaddel Could you explain the custom frequency settings?
